import Head from "next/head";
import React from "react";

const MetaData = () => {
  return (
    <div>
      <Head>
        <title>Munchkin Koneko Token</title>
        <meta name="description" content="Generated by Munchkin Koneko Token" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/res/headlogo_S.png" />
      </Head>
    </div>
  );
};

export default MetaData;
